export type { IDashcamRepository } from './IDashcamRepository'
export type { IContactRepository } from './IContactRepository'
export type { ISendRecommendationRepository } from './ISendRecommendationRepository'
export type { IClockPort } from './IClockPort'
export type { IDbHealthRepository } from './IDbHealthRepository'
export type { ILeadRepository } from './ILeadRepository'
export type { IGalleryRepository } from './IGalleryRepository'
