import type { IDashcamRepository } from '@/domain/dashcam/IDashcamRepository'
import type { DashcamProduct } from '@/domain/dashcam/DashcamProduct'

const PRODUCTS: DashcamProduct[] = [
  {
    id: 'hiwei-x1-pro',
    name: 'Hiwei X1 Pro',
    brand: 'Hiwei',
    description: 'La opción más popular para uso diario. Grabación frontal en alta definición con ángulo amplio de 140°.',
    price: 89990,
    priceDisplay: '$89.990 – $99.990 ARS',
    rating: 4.6,
    reviewCount: 214,
    specs: ['Full HD 1080p', 'Ángulo 140°', 'WDR nocturno', 'App móvil'],
    features: [
      'Resolución Full HD 1080p',
      'Ángulo de 140°',
      'Sensor de noche WDR',
      'G-Sensor integrado',
      'App móvil incluida',
    ],
    tags: ['popular', 'frontal', 'relación precio-calidad'],
    cameraPositions: ['frontal'],
    maxQuality: 'muy-buena',
    maxRecordingTime: '2h',
    supportsParking: false,
    supportsBluetooth: false,
    supportsInstallation: true,
  },
  {
    id: 'hiwei-x2-dual',
    name: 'Hiwei X2 Dual',
    brand: 'Hiwei',
    description: 'Cobertura delantera y trasera para máxima protección. Ideal para quienes quieren registrar todo lo que pasa en la ruta.',
    price: 149990,
    priceDisplay: '$149.990 – $165.000 ARS',
    rating: 4.7,
    reviewCount: 178,
    specs: ['Frontal 1080p', 'Trasera 720p', 'Parking mode', 'Bluetooth'],
    features: [
      'Cámara frontal Full HD 1080p',
      'Cámara trasera HD 720p',
      'Visión nocturna mejorada',
      'Pantalla LCD 2.4"',
      'Detección de movimiento',
    ],
    tags: ['doble cámara', 'frontal y trasera', 'protección total'],
    cameraPositions: ['frontal', 'frontal-trasera'],
    maxQuality: 'muy-buena',
    maxRecordingTime: '4h',
    supportsParking: true,
    supportsBluetooth: true,
    supportsInstallation: true,
  },
  {
    id: 'hiwei-x3-ultra',
    name: 'Hiwei X3 Ultra',
    brand: 'Hiwei',
    description: 'El modelo más completo de la línea. Triple cámara con calidad superior y modo estacionamiento avanzado.',
    price: 249990,
    priceDisplay: '$249.990 – $275.000 ARS',
    rating: 4.9,
    reviewCount: 89,
    specs: ['4K Ultra HD', 'GPS integrado', 'Parking 24hs', 'Triple cámara'],
    features: [
      'Cámara frontal 4K Ultra HD',
      'Cámara trasera Full HD 1080p',
      'Cámara interior HD',
      'GPS integrado',
      'Modo estacionamiento 24hs',
      'Control Bluetooth',
    ],
    tags: ['triple cámara', 'ultra HD', 'premium', 'GPS'],
    cameraPositions: ['frontal', 'frontal-trasera', 'frontal-trasera-interior'],
    maxQuality: 'superior',
    maxRecordingTime: '8h',
    supportsParking: true,
    supportsBluetooth: true,
    supportsInstallation: true,
  },
  {
    id: 'hiwei-s1-basic',
    name: 'Hiwei S1 Basic',
    brand: 'Hiwei',
    description: 'Compacta y sencilla. Perfecta para quien busca registrar el viaje sin complicaciones a un precio accesible.',
    price: 49990,
    priceDisplay: '$49.990 – $59.990 ARS',
    rating: 4.3,
    reviewCount: 312,
    specs: ['HD 720p', 'Ángulo 120°', 'Plug & play', 'Bucle automático'],
    features: [
      'Resolución HD 720p',
      'Ángulo de 120°',
      'Grabación en bucle automática',
      'Instalación plug & play',
    ],
    tags: ['económico', 'básico', 'frontal'],
    cameraPositions: ['frontal'],
    maxQuality: 'muy-buena',
    maxRecordingTime: '1h',
    supportsParking: false,
    supportsBluetooth: false,
    supportsInstallation: true,
  },
  {
    id: 'hiwei-x2-plus',
    name: 'Hiwei X2 Plus',
    brand: 'Hiwei',
    description: 'Frontal y trasera con calidad superior y pantalla táctil. El equilibrio perfecto entre precio y prestaciones.',
    price: 189990,
    priceDisplay: '$189.990 – $210.000 ARS',
    rating: 4.8,
    reviewCount: 143,
    specs: ['2K QHD', 'Wi-Fi', 'Parking mode', 'Pantalla táctil 3"'],
    features: [
      'Cámara frontal 2K QHD',
      'Cámara trasera Full HD 1080p',
      'Pantalla táctil IPS 3"',
      'Wi-Fi integrado',
      'Modo estacionamiento',
      'Control Bluetooth incluido',
    ],
    tags: ['calidad superior', 'frontal y trasera', 'wifi'],
    cameraPositions: ['frontal', 'frontal-trasera'],
    maxQuality: 'superior',
    maxRecordingTime: '4h',
    supportsParking: true,
    supportsBluetooth: true,
    supportsInstallation: true,
  },
]

export class InMemoryDashcamRepository implements IDashcamRepository {
  getAll(): DashcamProduct[] {
    return PRODUCTS
  }

  getById(id: string): DashcamProduct | undefined {
    return PRODUCTS.find((p) => p.id === id)
  }
}
